### ISSUE TITLE
remove Pycluster dependency

### ISSUE THREAD

**Issue by simonvh** [simonvh/fluff#38]
For easier install with dependencies (pip, conda), replace Pycluster with clustering from scipy (if possible, otherwise use sklearn).

**Comment by Jorisvansteenbrugge** [comment]
I experienced this error when installing Pita as well. When looking into licenses I found that Pycluster is under the Python license. Stating on python's website: 
> All Python licenses let you distribute
    a modified version without making your changes open source

I think you could include Pycluster in the package to avoid the installation error (as a temporary or final solution).
