### ISSUE TITLE
trouble in installing biofluff, pycluster not found

### ISSUE THREAD

**Issue by amoltej** [simonvh/fluff#52]
hello, 
can some body please help me with installing biofluff?
I ran "sudo pip install biofluff" command.
here is the outcome i see - 

Requirement already satisfied (use --upgrade to upgrade): biofluff in /usr/lib/python2.7/site-packages/biofluff-2.1.0-py2.7.egg
Requirement already satisfied (use --upgrade to upgrade): pysam in /usr/lib64/python2.7/site-packages (from biofluff)
Collecting HTSeq (from biofluff)
  Downloading HTSeq-0.6.1.tar.gz (226kB)
    100% |████████████████████████████████| 235kB 3.5MB/s
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/lib64/python2.7/site-packages (from biofluff)
Requirement already satisfied (use --upgrade to upgrade): scipy in /usr/lib64/python2.7/site-packages (from biofluff)
Requirement already satisfied (use --upgrade to upgrade): matplotlib in /usr/lib64/python2.7/site-packages (from biofluff)
Collecting colorbrewer (from biofluff)
  Downloading colorbrewer-0.1.1.tar.gz
Collecting pybedtools (from biofluff)
  Downloading pybedtools-0.7.7.tar.gz (12.6MB)
    100% |████████████████████████████████| 12.6MB 70kB/s
Collecting Pycluster (from biofluff)
  Could not find a version that satisfies the requirement Pycluster (from biofluff) (from versions: )
No matching distribution found for Pycluster (from biofluff)

Thanks 
AMoL

**Comment by georgeg9** [comment]
Hello AMoL,

Try to install Pycluster using the following command:

pip install
http://bonsai.hgc.jp/~mdehoon/software/cluster/Pycluster-1.52.tar.gz

George

**Comment by amoltej** [comment]
That's great .. it worked.. Thank you so much George

AMoL
