### ISSUE TITLE
when plot heatmap using bigwig files

### ISSUE THREAD

**Issue by xzdai** [simonvh/fluff#53]
Hi,
I am impressed by the heatmap parts in fluff. 
I can get the plot from the example, but this error came up when I use own data:
## CMD

$ fluff heatmap -f tsses_1kb.bed -d WT_H2A_Z.bw arp6_H2A.Z.bw WT_H3K4me3.bw arp6_H3K4me3.bw  -o test_heatmap

Euclidean distance method
Loading data
[bwGetOverlappingIntervalsCore] Got an error

I can use the bigwig files to plot the profiles of select genes, but it doesn't work when use the bw files to plot the heatmap.

Please help me! Thank you very much!

Xiaozhuan Dai

**Comment by georgeg9** [comment]
Hello Xiaozhuan Dai,

Thank you for using fluff:)

That's really strange error. I tried now with some of our data and it works fine. Can you check if all the files are ok or, If you don't mind, can you please share some of your data? I want to trace back the error and see where exactly is the problem.

George

**Comment by simonvh** [comment]
This could be related to a bug in handling .bw files, see a1dd684. This will be incorporated in fluff 2.1.1.

**Comment by simonvh** [comment]
As there was no further input, I'm closing this issue. Feel free to open a new issue if necessary!
