### ISSUE TITLE
Is it possible to set different y axis for each track shown on fluff profile image ?

### ISSUE THREAD

**Issue by AlicePsyche** [simonvh/fluff#54]
Hi, 

I would like to use fluff profile to show my tracks, is it possible to manually set different vertical viewing range(y axis) for each track like UCSC genome browser ?

By the way, can I set different colors for each track by `-c` option ? 

Thanks for your help !

**Comment by simonvh** [comment]
Yes, both are possible! For example, let's say I run the following command:

```
fluff profile -i chr1:167100000-167200000 \
 -d H1_H3K27ac.bam mesendoderm_H3K27ac.bam neuronal_progenitor_H3K27ac.bam  \
 -o profile.png
```
This would result in the following picture:

![profile](https://cloud.githubusercontent.com/assets/281252/17921942/bc9c2774-69dc-11e6-95fc-c8f07664a549.png)

Now I can change both scale as well as color.

```
fluff profile -i chr1:167100000-167200000 \
 -d H1_H3K27ac.bam mesendoderm_H3K27ac.bam neuronal_progenitor_H3K27ac.bam \
 -c purple,#386cb0,orange -S 100,300,300 -o profile2.png
```

With this as result:

![profile2](https://cloud.githubusercontent.com/assets/281252/17921974/e467ee32-69dc-11e6-8eb6-b7291194eefe.png)

For colors you can use color names, or hex code if you want to have more control. If you specify one of the [ColorBrewer palette names](https://bl.ocks.org/mbostock/5577023) fluff will cycle through this palette for every track.

**Comment by AlicePsyche** [comment]
That's odd...When I run, I got the error message: 

`biofluff                  2.1.0                    py27_0    bioconda`

```
fluff profile -i chr18:14184022-14546879 -d ../bwfiles/K27ac_smooth.bw ../bwfiles/K27Ac_145.bw \ ../bwfiles/K27ac_155.bw \ 
../bwfiles/K27Ac_190.bw ../bwfiles/K27ac_142.bw ../bwfiles/K27Ac_237.bw \ ../bwfiles/K27Ac_255.bw ../bwfiles/K27ac_195.bw \ 
../bwfiles/k27ac_348.bw \
-o K27ac_snapshot \
-S 100,60,60,40,40,40,60,60,100 \ 
-a /database/genome/zebrafish_refFlat.bed \ 
-c #32cd32,purple,purple,#386cb0,#386cb0,#386cb0,orange,orange,orange \ 
-b white
```

The error message: 
```
usage: fluff [-h] [options] profile [-i INTERVAL] -d [FILE [FILE ...]] -o name
                                    [-n] [-a FILE] [-t GROUPS] [-s GROUPS]
                                    [-S INT] [-f FRAGMENTSIZE] [-D] [-R] [-r]
                                    [-c NAMES] [-b BACKGROUND]
                                    [-T TEXTFONTSIZE] [-H] [-h]
fluff [-h] [options] profile: error: argument -c: expected one argument
```

What's the possible problem ?

**Comment by simonvh** [comment]
Can you try the same command, but with the -c argument quoted:

```
-c "#32cd32,purple,purple,#386cb0,#386cb0,#386cb0,orange,orange,orange" \
```

**Comment by AlicePsyche** [comment]
OH! It worked! Thanks for your kindly help! 

I love fluff to plot figures, it is easy to use and you guys have superb taste for beauty :)  The only problem is its documentation... Sometimes it has too little information to be understood. I recommended it to many my non-bioinfo classmates while they kept asking me detail usage. I think if its documentation could be more user-friendly, it will definitely attract many people. [Deeptools](http://deeptools.readthedocs.io/en/latest/content/list_of_tools.html) is a good example. Please don't let fluff be buried because of something could be avoided. 

Thanks again.

**Comment by simonvh** [comment]
I'm glad it works. Thanks for your feedback on the documentation, it is a valid point.
