### ISSUE TITLE
Exception in thread Thread-3

### ISSUE THREAD

**Issue by descostesn** [simonvh/fluff#56]
Hi,

When running heatmap I get the following error and nothing happens. The program just keeps running. Want to let you know that I am ignorant in Python. thanks.

`Warning: Running fluff with too many files might make you system use enormous amount of memory!
Euclidean distance method
Loading data
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 380, in _handle_results
    task = get()
TypeError: ('__init__() takes exactly 3 arguments (1 given)', <class 'pybedtools.helpers.BEDToolsError'>, ())`

**Comment by georgeg9** [comment]
Hello @kitano902 ,

Which version of pybedtools do you have? You can find out using this command:

`pip freeze | grep pybedtools`

George

**Comment by kitano902** [comment]
I get pybedtools==0.7.8

thanks

**Comment by georgeg9** [comment]
Can you send me the first few lines from your BED file?

**Comment by kitano902** [comment]
Basically I copied what you used in the tutorial:

chr1	1045278	1045278	0
chr1	1371026	1371026	0
chr1	1690476	1690476	0
chr1	2107526	2107526	0
chr1	2131026	2131026	0
chr1	2136376	2136376	0
chr1	2144276	2144276	0
chr1	3786676	3786676	0
chr1	5953272	5953272	0
chr1	6067656	6067656	0
chr1	6972146	6972146	0
chr1	8469473	8469473	0
chr1	8580639	8580639	0
chr1	8586076	8586076	0


what is strange is that it is working with BAM files but not wig files.

thanks again.

**Comment by simonvh** [comment]
@georgeg9  any updates here? Is this solved?

**Comment by simonvh** [comment]
I am closing this, due to lack of input. Feel free to re-open, if there are more details!
