### ISSUE TITLE
scale of bandplot

### ISSUE THREAD

**Issue by yfqin** [simonvh/fluff#57]
Hi ;
I am using fluff to generate bandplot. But the scale of same cluster in each group is different. This will be a little difficult for me to compare. Would you please fix that? And also add the mean signal as an option in bandplot. Median signal sometimes looks not no good.

YQ

**Comment by simonvh** [comment]
You can set the scale with the `-s` option, which allows you to use similar scales for different tracks. For instance, `-s 1:2,3:4` would set a shared scale for the first two tracks and another shared scale for the second two tracks. If your profile doesn't look too good in the bandplots, try decreasing the number of bins with the `-b` parameter, for instance to 20 or so. That usually helps.

**Comment by yfqin** [comment]
Thank you so much. It is really a good tools to generate the heatmap.



Yufeng Qin, Ph.D
Eukaryotic Transcriptional Regulation Group
Epigenetics & Stem Cell Biology Laboratory
National Institute of Environmental Health Sciences(NIEHS)

2016-11-17 6:07 GMT-05:00 Simon van Heeringen <notifications@github.com>:
