### ISSUE TITLE
Matplotlib deprecation

### ISSUE THREAD

**Issue by ChemaMD** [simonvh/fluff#59]
Hi, I just installed fluff with conda, which also installed Matplotlib v2.0.0. When running fluff profile, I get a warning message from Matplotlib:

`/Users/Chema/src/miniconda2/lib/python2.7/site-packages/fluff/plot.py:483: MatplotlibDeprecationWarning: The set_axis_bgcolor function was deprecated in version 2.0. Use set_facecolor instead.
  ax.set_axis_bgcolor(bgcol)`

Should I edit plot.py? Thanks

**Comment by simonvh** [comment]
Thanks for notifying! The DeprecationWarning will not infere with fluff functionality in any way. We will update this in a new version.

**Comment by simonvh** [comment]
Closed in bfd807a
