### ISSUE TITLE
apparent error in color.py 

### ISSUE THREAD

**Issue by sinclaircooper** [simonvh/fluff#60]
Hi Simon, 

I'm trying to to use fluff for the first time to generate some profile plots. I am getting the following error message when running "fluff profile -h "

Traceback (most recent call last):
  File "/usr/local/bin/fluff", line 4, in <module>
    __import__('pkg_resources').run_script('biofluff==2.1.0', 'fluff')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 698, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1616, in run_script
  File "/usr/local/lib/python2.7/dist-packages/biofluff-2.1.0-py2.7.egg/EGG-INFO/scripts/fluff", line 4, in <module>
    from fluff.parse import parse_args
  File "/usr/local/lib/python2.7/dist-packages/biofluff-2.1.0-py2.7.egg/fluff/parse.py", line 4, in <module>
    from fluff import commands
  File "/usr/local/lib/python2.7/dist-packages/biofluff-2.1.0-py2.7.egg/fluff/commands/__init__.py", line 10, in <module>
    m = __import__("{0}.{1}".format(__name__, cmdname), globals(), locals(), [cmdname], -1)
  File "/usr/local/lib/python2.7/dist-packages/biofluff-2.1.0-py2.7.egg/fluff/commands/bandplot.py", line 14, in <module>
    from fluff.color import parse_colors
  File "/usr/local/lib/python2.7/dist-packages/biofluff-2.1.0-py2.7.egg/fluff/color.py", line 47, in <module>
    DEFAULT_COLORS = get_pal("Set1")
  File "/usr/local/lib/python2.7/dist-packages/biofluff-2.1.0-py2.7.egg/fluff/color.py", line 42, in get_pal
    pal[i] = [x / 255.0 for x in pal[i][0]]
TypeError: unsupported operand type(s) for /: 'str' and 'float'

I had a look inside color.py and it seems to be trying to iterate through a string, rather than a list (which I guess is what was intended). Do you think this an issue with dependencies/versions (I'm thinking I have the wrong version of something installed) or just a bug?

Cheers
S

**Comment by simonvh** [comment]
First, sorry for taking so long to reply. 

I have to admit that I'm not sure what causes this issue. I have not seen this issue before, and it is not something that I can replicate? How did you install fluff? Which Python version are you using? 

@georgeg9 any ideas?

**Comment by sinclaircooper** [comment]
I'm using python 2.7. 

S

**Comment by simonvh** [comment]
Python version should be fine. What version of colorbrewer do you have installed?
Can you run the following piece of code (for instance in ipython) and post the results here? 

```
import colorbrewer
colorbrewer.__dict__["Set1"]
```

**Comment by sinclaircooper** [comment]
Hi, thanks for the reply. 

>>> import colorbrewer 
>>> colorbrewer.__dict__["Set1"]
Bunch(3=['rgb(228,26,28)', 'rgb(55,126,184)', 'rgb(77,175,74)'], 4=['rgb(228,26,28)', 'rgb(55,126,184)', 'rgb(77,175,74)', 'rgb(152,78,163)'], 5=['rgb(228,26,28)', 'rgb(55,126,184)', 'rgb(77,175,74)', 'rgb(152,78,163)', 'rgb(255,127,0)'], 6=['rgb(228,26,28)', 'rgb(55,126,184)', 'rgb(77,175,74)', 'rgb(152,78,163)', 'rgb(255,127,0)', 'rgb(255,255,51)'], 7=['rgb(228,26,28)', 'rgb(55,126,184)', 'rgb(77,175,74)', 'rgb(152,78,163)', 'rgb(255,127,0)', 'rgb(255,255,51)', 'rgb(166,86,40)'], 8=['rgb(228,26,28)', 'rgb(55,126,184)', 'rgb(77,175,74)', 'rgb(152,78,163)', 'rgb(255,127,0)', 'rgb(255,255,51)', 'rgb(166,86,40)', 'rgb(247,129,191)'], 9=['rgb(228,26,28)', 'rgb(55,126,184)', 'rgb(77,175,74)', 'rgb(152,78,163)', 'rgb(255,127,0)', 'rgb(255,255,51)', 'rgb(166,86,40)', 'rgb(247,129,191)', 'rgb(153,153,153)'])

**Comment by simonvh** [comment]
Could it be that you have [this colorbrewer](https://github.com/dsc/colorbrewer-python) package installed instead of [this one](https://pypi.python.org/pypi/colorbrewer)?

**Comment by sinclaircooper** [comment]
Great, fixed. Thanks Simon. I'm not sure how I ended up using other version. 

Sinclair

**Comment by simonvh** [comment]
I'm glad we could track down the issue :)
