### ISSUE TITLE
Meaning of "-e INT extend (in bp. Default: 5000)"

### ISSUE THREAD

**Issue by tianping** [simonvh/fluff#62]
There is an option (-e INT) for "fluff heatmap". The default value is 5000. I want to make sure of its meaning. Does it mean that reads will be extended from 5' to 3' (not bidirectionally) to a final length of 5000 bp?

**Comment by simonvh** [comment]
This is bidirectionally, so 5000 from both 5' and 3'.

**Comment by tianping** [comment]
thx
