### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by shenscore** [simonvh/fluff#79]
Hi,
    I install fluff by conda and update numpy to 1.15.1.
    no matter what command I run , I always get a "Segmentation fault".

**Comment by simonvh** [comment]
Can you provide some more detail? Which version of fluff do you have? What is the OS? Can you give the exact command and output that results in a Segmentation fault?

**Comment by shenscore** [comment]
I'm using linux and conda 3(version 4.5.11). The error message is just a single line of "Segmentation fault" and no matter what I type followed fluff always get this error.

I uninstalled fluff from conda and then reinstall it by creating a seperate env. Now I can use fluff.
