### ISSUE TITLE
replicable clusters based on k-means

### ISSUE THREAD

**Issue by JMing-Li** [simonvh/fluff#80]
Thanks for providing such user-friendly package!  The results of feature clusters are not repeatable when I use k-means through `fluff heatmap`  although the results are almost the same each time I run the same command. I guess it's because of k-means method. Is there a way to initialize the basic random number generator ?

**Comment by simonvh** [comment]
There is not at the moment, but it's a good point. Essential to have a replicable analysis. I'll add it.

**Comment by simonvh** [comment]
Once version 3.0.3 is available, you can use the `-S` option to set the random seed for K-means clustering.
